#workflow name
name: Learning
# run this workflow when any push detect on repositry
on:
  push:
    main
# A workflow which contains
jobs:
  # this is Job ids
  hello:
     # this tells github ti create fresh ubuntu VM and run my Jobs there
    runs-on: ubuntu-latest
    steps:
      -name: Say hello
      run: echo "hello i am aniket"

